<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludePath>$(IncludePath);$(ProjectDir)\libs\openssl-1.1.1b\include\;</IncludePath>
    <LibraryPath>$(LibraryPath);$(ProjectDir)\libs\openssl-1.1.1b\lib\;</LibraryPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.2.1" />
    <PackageReference Include="HttpMultipartParser" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
  </ItemGroup>

</Project>
